public Object run() throws Exception {
    return invokeInternal();
}