void internalPropagateException(Throwable ex) {
    // rethrow outside exec() catches.
    rethrow(ex);
}